import 'package:chatbot/models.dart';

List<Dialog> dialogs =[
  Dialog(0, 'immigration checkpoint', '입국 심사대', [
    Word('A : Can I see your passport?', '당신 여권 좀 볼 수 있을까요?'),
    Word('B : Sure. Here you are.', '물론이죠. 여기 있습니다.'),
    Word('A : Is this your first visit to Singapore?', '싱가포르에는 처음이신가요?'),
    Word('B : Yes, it is.', '네 맞아요'),
    Word('A : Where will you be staying', '어디에서 머무시나요?'),
    Word('B : I will be staying at the EF hotel.', 'EF호텔에서 머물어요'),
    Word('A : How long will you be staying?', '얼마나 오래 머무시나요?'),
    Word('B : I will be staying for three days.', '3일간 머물어요'),
    Word('A : Please enjoy your stay.', '좋은 휴가 보내세요'),
    Word('B : Thank you.', '감사합니다'),
  ]),
  Dialog(1, 'in a taxi', '택시에서', [
    Word('A : Where would you like to go?', '어디로 가고 싶으신가요?'),
    Word("B : I'd like to go to the EF hotel.", 'EF 호텔로 가고 싶어요.'),
    Word('A : O.K. No problem.', '알겠습니다. 걱정 마세요.'),
    Word('B : How long will it take?', '얼마나 걸리나요?'),
    Word('A : It is 20 minutes from here.', '여기서 20분 정도 걸립니다.'),
    Word('B : O.k. Thank you. Are you almost there?', '네. 감사합니다. 거의 다 왔나요?'),
    Word("A : Yes, we are. We will be there soon.", '네. 곧 도착해요.'),
    Word('B : How much is it?', '얼마인가요?'),
    Word("A : it's 19 dollars.", '19 달러 입니다.'),
    Word('B : Here you are. You can keep the change.', '여기있습니다. 잔돈은 괜찮아요.'),
    Word('A : Thanks a lot.', '감사합니다.'),
  ]),
  Dialog(2, 'Hotel Check-in', '호텔 체크인', [
    Word('A : Welcome to EF hotel. How may I help you?', 'EF 호텔에 오신걸 환영합니다. 뭘 도와드릴까요?'),
    Word("B : Can I check in now?", '체크인 할 수 있나요?'),
    Word('A : Sure. Can you tell me your name, please?', '물론이죠. 성함을 말씀해 주시겠어요?'),
    Word('B : My name is Zoomma', '제 이름은 줌마입니다.'),
    Word('A : Can you spell that for me, please?', '스펠링을 말씀해 주실 수 있나요?'),
    Word('B : Yep. Z-o-o-m-m-a.', '넵, Z-o-o-m-m-a입니다.'),
    Word("A : Yes, Mrs. zoomma. We've reserved a room for you.", '네, 줌마씨. 당신을 위한 방이 예약되어 있네요'),
    Word('B : Can you tell me the room number, please?', '호실 번호를 알려주실 수 있나요?'),
    Word("A : Your room number is 567.", '호실 번호는 567입니다.'),
    Word('B : Thank you. By the way, what time should I check out?', '감사합니다. 그런데 몇시까지 체크아웃인가요?'),
    Word('A : 12:00 noon', '오후 12시 정각입니다.'),
    Word('B : Great, Have a good day', '좋아요. 좋은하루 보내세요.'),
  ]),
  Dialog(3, 'At a Restaurant', '음식점에서', [
    Word('A : Welcome to EF streakhouse. How may I help you?', 'EF 스테이크 하우스에 오신걸 환영합니다. 뭘 도와드릴까요?'),
    Word("B : Can I have a table for two people, please?", '2명 자리 있나요?'),
    Word('A : No problem.', '네 물론이죠'),
    Word('B : Thanks. This is my first time here. Can you help me, please.', '감사합니다. 여기 처음이예요. 좀 도와주시겠어요?'),
    Word('A : Sure.', '물론이죠'),
    Word('B : Any recommendations?', '추천할만한거  있나요?'),
    Word("A : Well, I would recommend the Irish beef streak.", '흐음, 저는 Irish 소고기 스테이크를 추천해요'),
    Word("B : Oh, That sounds good. I'll have it.", '오 좋아요. 그걸로 할게요.'),
    Word("A : Anything else?", '더 필요하신거 있나요?'),
    Word('B : Can I get some more water, please?', '물 좀 가져다 주시겠어요?'),
    Word("A : No problem. I'll be right back", '물론이죠. 금방 가져다 드릴게요.'),
    Word('B : Thanks', '감사합니다.'),
  ]),
  Dialog(4, 'Getting a Dessert', '후식 시키기', [
    Word('A : How was your dinner?', '저녁 어떠셨어요?'),
    Word('B : It was great, thanks.', '좋았어요, 고마워요'),
    Word('A : Would you like something for dessert?', '후식 드실래요?'),
    Word('B : Yes, what kind of dessert do you have?', '좋아요, 어떤 종류의 후식이 있나요?'),
    Word('A : We have chocolate mousse cake and strawberry cake for dessert', '초콜렛 무스 케이크랑 딸기 케잌이 있어요'),
    Word('B : Then can we have chocolate mousse cake?', '초콜렛 무스 케이크 먹을까요?'),
    Word('A : Sure. Would you like coffee or tea?', '좋아. 커피나 차 필요하신가요?'),
    Word('B : Can you bring us four cups of coffee, please?', '커피 4잔 가져다 주실 수 있나요?'),
    Word('A : I will be right back with your dessert and coffee', '후식과 커피를 금방 가져다 드리겠습니다.'),
    Word('B : Thank you for the help', '도와주셔서 감사합니다'),
    Word('A : Not a problem', '천만에요'),
  ]),
  Dialog(5, 'Asking for Directions', '길 물어보기', [
    Word('A : Excuse me?', '저기요?'),
    Word('B : Yes?', '네?'),
    Word("A : I'm new here. Can you tell me how to get to the EF hotel, please?", '저는 여기가 처음이예요. EF 호텔까지 가는 방법을 알려주실수 있나요?'),
    Word('B : Oh, no problem, Actually you are not far away at all', '오, 걱정 마세요, 여기에서 멀지 않아요'),
    Word('A : O.K. how long will it take from here?', '알겠습니다. 여기서 얼마나 가야하나요?'),
    Word("B : it's about a 5 minute walk", '걸어서 5분 정도 걸려요'),
    Word('A : Great. How do I get there?', '좋네요. 어떻게 가아하죠?'),
    Word('B : Go along this road until you get to the 5th Avenue', '5번가에 도착할 때까지 이 길을 따라 가세요.'),
    Word('A : 5th Avenue?', '5번가요?'),
    Word('B : Right, Make a right turn there. Then, the EF hotel will be on your right.', '맞아요, 거기서 우회전 하세요. 그러면 EF호텔이 오른쪽에 있을 거예요.'),
    Word('A : Thanks a million', '정말 감사합니다'),
    Word('B : You are welcome', '천만에요'),
  ]),
  Dialog(6, 'At a Shopping Mall', '쇼핑몰에서', [
    Word('A : May I help you?', '도와 드릴까요?'),
    Word('B : Yes please. Do you have long-sleeve shirts?', '네 부탁해요. 긴팔 셔츠 있나요?'),
    Word('A : Yes, they are right here.', '네, 여기 있습니다.'),
    Word('B : How much are they?', '얼마인가요?'),
    Word('A : They are 15 dollars each.', '각각 15달러 입니다.'),
    Word('B : Do you have any larger sizes?', '더 큰 사이즈는 있나요?'),
    Word('A : What about these? There are larger and more colorful.', '이건 어때요? 더 크고 더 컬러풀한 색상이예요.'),
    Word('B : This one looks good. Can I try this on?', '이거 좋아보인다. 이거 입어봐도 되나요?'),
    Word('A : Sure. The fitting room is over there.', '물론이죠. 탈의실은 저쪽입니다.'),
    Word('B : What do you think?', '어떤거 같나요?'),
    Word('A : That looks really good on you.', '정말 잘어울려요'),
    Word('B : Thanks. I will take this', '감사합니다. 이걸로 할게요'),
  ]),
  Dialog(7, 'Hotel Check-out', '호텔 체크아웃', [
    Word('A : Hi. May I help you?', '안녕하세요. 도와드릴까요?'),
    Word('B : Yes please. Can I check out?', '네 부탁해요. 체크아웃 할 수 있나요?'),
    Word('A : No problem. May I ask your name?', '물론이죠. 성함을 물어봐도 될까요?'),
    Word('B : Sure. My name is Zoomma', '물론이죠. 제 이름은 줌마예요'),
    Word("A : Did you take anything from the minibar?", '미니바에서 뭐 드신거 있나요?'),
    Word("B : No. I didn't", '아니요. 안먹었어요'),
    Word("A : O.K. Let me see. The total comes to 134 dollars. How would you like to pay?", '알겠습니다. 어디 봅시다. 총 134달러입니다. 결제는 어떻게 하시겠습니까?'),
    Word("B : I'll pay with credit card", '신용카드로 할게요.'),
    Word('A : O.K. How was everything?', '알겠습니다. 어떠셨나요?'),
    Word("B : Everything was great", '모든게 좋았습니다.'),
    Word("A : That's good to hear. Thank you again for staying at the EF hotel.", '듣던 중 반가운 소리네요. EF 호텔에 묵어줘서 다시 한번 감사합니다.'),
    Word("B : Thank you also for your great service", '저 또한 당신의 좋은 서비스에 감사합니다.'),
  ]),
  Dialog(8, 'Checking In at the Airport', '비행기 탑승 수속', [
    Word("A : Good afternoon, Can I see your ticket and passport?", '안녕하십니까, 티켓과 여권을 보여주시겠습니까?'),
    Word('B : Sure, here you are', '물론이죠, 여기있습니다.'),
    Word('A : Will you be checking any luggage?', '짐 부치시겠습니까?'),
    Word('B : Yes, I have one bag', '네, 가방 하나요.'),
    Word('A : Can you put your luggage on the scale?', '짐을 저울에 올려 주시겠습니까?'),
    Word('B : No problem', '물론이죠.'),
    Word('A : Do you have any carry-on bags?', '가지고 타시는 가방이 있나요?'),
    Word('B : Yes, I have one small bags with me.', '네, 작은 가방 하나 들고 탈겁니다.'),
    Word('A : Do you want a window seat or an aisle seat?', '창가 쪽 좌석으로 하시겠습니까, 통로 쪽 좌석으로 하시겠습니까?'),
    Word('B : I would like a window seat, please.', '창가 쪽으로 부탁해요'),
    Word('A : O.k. Here is your boarding pass, Your gate number is B7. Enjoy your flight', '네, 여기 탑승권 여기 있습니다, 탑승구 번호는 B7입니다. 즐거운 비행 되십시오.'),
    Word('B : Thank you', '감사합니다.'),

  ]),
  Dialog(9, 'In Flight', '기내에서', [
    Word('A : Would you like something to drink?', '마실 것 좀 드시겠어요?'),
    Word('B : Can I have some water please?', '물 좀 주시겠습니까?'),
    Word('A : No problem, I will be right back.', '물론이죠, 금방 돌아올게요.'),
    Word('A : Here you are. Do you need anything else?', '여기있습니다. 더 필요한거 있으신가요?'),
    Word('B : Can I have some more peanuts, please?', '땅콩 좀 더 주시겠습니까?'),
    Word('A : Sure', '물론이죠.'),
    Word('A : Would you like chicken or beef?', '닭고기로 하시겠습니까, 소고기로 하시겠습니까?'),
    Word('B : Chicken, please.', '닭고기로 부탁해요.'),
    Word('A : What would you like to drink?', '뭐 마실거 드릴까요??'),
    Word('B : Can I have some tea?', '차 있나요?'),
    Word('A : No problem, Anything else?', '물론이죠, 더 필요한건 없으신가요?'),
    Word("B : That's it. Thank you.", '그거예요, 감사합니다.'),
    Word('B : Excuse me. May I have one more blanket please?', '실례합니다만 담요 한 장만 더 주시겠습니까?'),
    Word('A : Sure. I will be right back.', '물론이죠, 금방 가져다 드릴게요.'),
  ]),
  Dialog(10, 'Currency Exchange', '환전소에서', [
    Word('A : Excuse me?', '저기요?'),
    Word('B : Hi! How can I help you?', '안녕하세요! 도움 드릴까요?'),
    Word('A : I would like to exchange korean won into U.S.dollars.', '저는 한국 원화를 미국 달러화로 바꾸고 싶어요.'),
    Word('B : O.K. No problem.', '네. 문제 없어요.'),
    Word('A : Can I have three 100 dollar bills?', '100달러짜리 지폐 세 장 주시겠습니까?'),
    Word('B : Sure.', '물론이죠.'),
    Word('A : Thank you.', '감사합니다.'),
    Word('B : Can you write your phone number and sign here, please', '여기에 전화번호를 적고 서명해 주시겠습니까?'),
    Word('A : Not a problem', '물론이죠'),
    Word('B : Here you are. Have a nice day.', '여기있습니다. 좋은 하루 보내세요.'),
    Word('A : You too have a nice day.', '당신도 좋은하루 보내세요.'),
  ]),
  Dialog(11, 'Renting a car', '자동차 빌리기', [
    Word("A : Excuse me? I'd like to rent a car", '저기요? 차 렌트하고 싶습니다.'),
    Word('B : Ok. We have compact cars, midsize cars, and vans', '좋아요. 저희는 소형차, 중형차, 밴이 있습니다.'),
    Word('A : Can you tell me how much they are?', '그것들이 얼마인지 말해줄 수 있나요?'),
    Word('B : Compact is 12 dollars, midsize is 24 dollars, and vans are 40 dollars a day', '하루 대여 시 소형차는 12달러, 중형차는 24달러, 밴은 40달러 입니다.'),
    Word('A : Then, Could I get a compact car?', '그럼, 소형차를 빌릴 수 있을까요?'),
    Word('B : How long will you rent the car?', '얼마나 오래 차를 빌릴 겁니까?'),
    Word('A : Three days', '3일이요.'),
    Word('B : Would you like insurance?', '보험이 필요하신가요?'),
    Word('A : Yes, How much is it?', '네, 얼마인가요?'),
    Word('B : It’s 10 dollars  a day', '하루에 10달러입니다.'),
    Word('A : Ok, Good', '네 좋네요'),
    Word('B : Please write your name and address here. Your car is ready outside now', '여기에 성함과 주소를 쓰십시오. 차는 지금 밖에 준비되어 있습니다.'),
    Word('A : Thanks a lot', '감사합니다.'),
  ]),
  Dialog(12, 'Making a hotel reservation', '호텔 예약하기', [
    Word("A : Hi, I'd like to make a reservation for this weekend", '안녕하세요, 이번주에 예약을 하고 싶은데요'),
    Word('B : Yes, we have several rooms available. How long will you stay?', '네, 몇 개의 방이 남아 있습니다. 얼마나 머무르실 겁니까?'),
    Word('A : We will probably stay for one night', '아마도 하루 머물거 같습니다.'),
    Word('B : How many people is the reservation for?', '예약 인원은 몇 명 입니까?'),
    Word('A : There will be two of us', '두명입니다.'),
    Word('B : Would you like a room with twin beds or a double bed?', '트윈 베드가 있는 방으로 하시겠습니까, 더블 베드가 있는 방으로 하시겠습니까?'),
    Word('A : Twin beds, please', '트윈 베드로 부탁합니다.'),
    Word('B : May I have your name, please?', '성함이 어떻게 되시죠?'),
    Word('A : My name is zoomma', '제 이름은 줌마입니다.'),
    Word('B : Thanks, can I have your credit card information?', '감사합니다, 신용카드 정보 좀 알려주실래요?'),
    Word("A : Sure. I'm using master card and the last numbers is 9942", '물론이죠. 저는 마스터 카드를 사용하고 있고 마지막 번호는 9942입니다.'),
    Word("B : Thank you so much. You're all set", '정말 감사합니다. 준비 다 됐습니다.'),
    Word('A : Thanks a lot', '감사합니다'),
  ]),
  Dialog(13, 'Room service', '룸서비스 시키기', [
    Word('A : Good morning. Room service, how may I help you?', '좋은아침입니다. 룸서비스입니다, 무엇을 도와드릴까요?'),
    Word('B : This is Zoomma in room 543. can I have some breakfast, please?', '543호에 있는 줌마 입니다. 아침식사 좀 주시겠습니까?'),
    Word('A : No problem. What would you like?', '물론이죠. 무엇을 드시겠습니까?'),
    Word("B : I'd like some scrambled eggs, bacon and some toast please.", '스크램블 에그랑 베이컨이랑 토스트로 부탁해요.'),
    Word('A : Not a problem. Do you need some coffee, too?', '문제 없어요. 커피도 필요하십니까?'),
    Word('B : Yeah, of course. Thanks. How long will it take?', '그래요, 물론입니다. 고마워요. 얼마나 걸릴까요?'),
    Word('A : It will take about 10 minutes.', '10분 정도 걸립니다.'),
    Word("B : That's perfect. Thanks", '완벽해요. 감사합니다.'),
  ]),
  Dialog(14, 'Buying a camera', '카메라 구입하기', [
    Word('A : Hello, How may I help you?', '안녕하십니까? 무엇을 도와드릴까요?'),
    Word('B : I would like to buy a camera', '저는 카메라를 사고 싶습니다.'),
    Word('A : Is there any brand you are looking for?', '봐둔 브랜드 있으신가요?'),
    Word('B : I would like to buy a samsung camera', '삼성 카메라를 사고 싶어요.'),
    Word('A : Not a problem. You can come and see what we have here', '문제 없어요. 여기 와서 저희가 뭘 가지고 있는지 봐보세요'),
    Word('A : Could I see the blue one?', '파란 것 좀 볼 수 있을까요?'),
    Word('B : Sure. Here you are.', '네, 여기있습니다.'),
    Word('A : Can you tell me how much that is?', '얼마인가요?'),
    Word('B : It’s 250 dollars', '250 달러 입니다.'),
    Word('A : I think it’s a bit more expensive than I thought', '생각보다 조금 비싼 것 같네요.'),
    Word('B : What about this one? This is cheaper', '이건 어때요? 이것은 더 저렴합니다.'),
    Word('A : Is it on sale?', '세일 중인가요?'),
    Word("B : Yes it is. It's only 179 dollars", '네 맞아요. 179달러밖에 안 되요.'),
    Word('A : Well, I think I will buy the cheaper one', '음, 저는 더 싼 것을 살 것 같아요.'),
  ]),
  Dialog(15, 'Asking someone to Take a photo', '사진 찍어달라고 부탁하기', [
    Word('A : Excuse me?', '실례합니다만?'),
    Word('B : Yes?', '네?'),
    Word('A : Would you mind taking a photo of us?', '저희 사진 좀 찍어 주시겠습니까?'),
    Word('B : Of course not. Just show me what to do with the camera', '물론이지요. 카메라 어떻게 사용 하는지 보여주세요.'),
    Word('A : Here’s the camera. Just press this button to take a picture', '카메라 여기 있습니다. 사진을 찍으려면 이 버튼을 누르십시면 되요.'),
    Word('B : All right, Say cheese', '좋아요, 치즈라고 말하세요.'),
    Word('A : Cheese', '치즈'),
    Word('B : One, two, three (click)', '하나, 둘, 셋 (클릭)'),
    Word('A : Thanks a million. Have a good day!', '정말 감사합니다. 좋은 하루 보내세요'),
    Word('B : You’re very welcome.', '천만에요'),
  ]),
  Dialog(16, 'At a supermarket', '슈퍼마켓에서', [
    Word('A : Execuse me?', '실례합니다만?'),
    Word('B : Yes, How can I help you?', '네, 무엇을 도와 드릴까요?'),
    Word('A : I am looking for the fruit section. Could you tell me where it is?', '저는 과일 코너를 찾고 있어요. 그곳은 어디에 있나요?'),
    Word('B : They are on aisle four', '4번 통로에 있어요'),
    Word('A : Thank you, by the way, do you have any sales today?', '감사합니다, 그런데 오늘 세일 있나요?'),
    Word('B : The strawberries and orange are on sale', '딸기와 오렌지를 세일하고 있어요.'),
    Word('A : Thank you for your help', '도와주셔서 감사합니다.'),
    Word('B : You can also find some asian foods on aisle 11', '11번 통로에서 아시아 음식도 찾을 수 있어요.'),
    Word('A : Thank you', '감사합니다.'),
  ]),
  Dialog(17, 'In a Hospital', '병원에서', [
    Word('A : How are you today?', '오늘 어때요?'),
    Word("B : I'm not feeling well now", '지금은 몸이 안 좋아요.'),
    Word("A : let's see", "한번 봐봅시다."),
    Word("B : I've got a headache and a fever.", '머리가 아프고 열이 나요.'),
    Word('A : How long have you been sick?', '아픈지는 얼마나 되었나요?'),
    Word('B : For about 2 days. ', '이틀 되었어요.'),
    Word('A : Do you have a cough, too?', '기침도 하나요?'),
    Word('B : Yes, sometimes I do', '네, 가끔 해요.'),
    Word('A : Do you have body aches, too?', '몸살 기운도 같이 있나요?'),
    Word('B : Yes, I do', '네, 맞아요'),
    Word('A : Well, it seems like you have the flu, Let me give you a prescription. Take pills after your meals', '음, 독감에 걸린 것 같은데요, 약을 처방해 드릴게요. 식사 후에 약을 복용하세요.'),
    Word('B : What else should I do?', '또 어떻게 해야 하죠?'),
    Word('A : You should drink lots of warm water', '따뜻한 물을 많이 마시세요'),
    Word('B : Thanks a lot', '정말 감사합니다.'),
  ]),
  Dialog(18, 'Getting a souvenir', '기념품 구매하기', [
    Word('A : Can you please show me where the T-shirt are?', '티셔츠가 어디 있는지 가르쳐 주시겠습니까?'),
    Word("B : They're right over here.", '바로 여기 있습니다.'),
    Word("A : Thanks, but actually I'm not sure about the size", '감사해요, 하지만 사실 사이즈를 잘 모르겠어요.'),
    Word('B : Is your friend about my size?', '당신의 친구는 제 사이즈 정도 되나요??'),
    Word('A : Well, I think my friend is a bit taller than you', '글쎄요, 제 친구가 당신보다 키가 조금 큰 것 같아요.'),
    Word("B : Ok. In that case, you'll need a large", '좋아요. 그렇다면, 큰 사이즈가 필요하겠군요.'),
    Word('A : Can you please recommend any gift for my sister?', '제 여동생에게 줄 선물 좀 추천해 줄래요?'),
    Word('B : How about some jewelry?', '주얼리는 어때요?'),
    Word('A : This necklace looks nice. How much is it?', '이 목걸이는 좋아 보여요. 얼마 입니까?'),
    Word("B : It's 120 dollars", '120 달러 입니다.'),
    Word('A : Can you give me a box for the necklace, please?', '이 목걸이를 위한 상자를 주시겠습니까?'),
    Word('B : Sure', '물론이죠'),
  ]),
];

/*
final dialog = [
  'immigration checkpoint',
  'In a Taxi',
  'Hotel Check-in',
  'At a Restaurant',
  'Getting a Dessert',
  'Asking for Directions',
  'At a Shopping Mall',
  'Hotel Check-out',
  'Checking In at the Airport',
  'In Flight',
  'Currency Exchange',
  'renting a car',
  'making a hotel reservation',
  'Room service',
  'Buying a camera',
  'Asking someone to Take a photo',
  'At a supermarket',
  'In a Hospital',
  'Getting a souvenir'];
 */